# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
      MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
      spring_profiles_active: github
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Setup SQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'company' # Optional, default value is "test". The specified database which will be create
        mysql root password: ${{ secrets.MYSQL_DB_PASSWORD }}  # Required if "mysql user" is empty, default is empty. The root superuser password

    - name: Build with Maven
      run: mvn -B package --file ./risk-analysis/pom.xml
    - run: mkdir staging && cp risk-analysis/target/risk-analysis-0.0.1-SNAPSHOT.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging

    # - name: Publish to GitHub Packages Apache Maven
    #   run: |
    #     cd risk-analysis
    #     mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
